bootstrapp_readme:
    path:  /
    defaults: { _controller: BootstrappBundle:Doc:readme }
    methods: [GET]
bootstrapp_demo:
    path:  /demo
    defaults: { _controller: BootstrappBundle:Doc:demo }
    methods: [GET]
bootstrapp_eyecon:
    path:  /demo/eyecon
    defaults: { _controller: BootstrappBundle:Doc:eyecon }
    methods: [GET, POST]
bootstrapp_jqueryui:
    path:  /demo/jqueryui
    defaults: { _controller: BootstrappBundle:Doc:jqueryui }
    methods: [GET, POST]
bootstrapp_pickadate:
    path:  /demo/pickadate
    defaults: { _controller: BootstrappBundle:Doc:pickadate }
    methods: [GET, POST]
bootstrapp_mobiscroll:
    path:  /demo/mobiscroll
    defaults: { _controller: BootstrappBundle:Doc:mobiscroll }
    methods: [GET, POST]
bootstrapp_ckeditor:
    path:  /demo/ckeditor
    defaults: { _controller: BootstrappBundle:Doc:ckeditor }
    methods: [GET, POST]
bootstrapp_redactor:
    path:  /demo/redactor
    defaults: { _controller: BootstrappBundle:Doc:redactor }
    methods: [GET, POST]
bootstrapp_fontawesome:
    path:  /demo/fontawesome
    defaults: { _controller: BootstrappBundle:Doc:fontawesome }
    methods: [GET, POST]
bootstrapp_select2:
    path:  /demo/select2
    defaults: { _controller: BootstrappBundle:Doc:select2 }
    methods: [GET, POST]
bootstrapp_elfinder_demo:
    path:  /demo/elfinder
    defaults: { _controller: BootstrappBundle:Doc:elfinder }
    methods: [GET, POST]

