bootstrapp_locales:
    path:   /_internal/bootstrapp/locales/{route}/{routeParams}/{locale}
    defaults:  { _controller: BootstrappBundle:Intl:locales }

bootstrapp_elfinder:
    resource: "@BootstrappBundle/Controller/ElFinderController.php"
    type:     annotation
