parameters:
    # CKEditor
    bootstrapp.ckeditor.base_path: bundles/bootstrapp/css/ckeditor/
    bootstrapp.ckeditor.class: nmariani\Bundle\BootstrappBundle\Form\Type\CKEditorType
    bootstrapp.ckeditor.default_config: full
    # elFinder
    bootstrapp.elfinder.roots:
        - {path: %kernel.root_dir%/../web/files/, URL: /files/}
    bootstrapp.locales: [en_US,fr_FR]
    # choice
    form.type.choice.widget: select2
    # datetime
    form.type.date.widget: eyecon
    form.type.date.format: 1 # 16 juillet 1983
    form.type.time.widget: jdewit
    form.type.time.format: ~
    form.type.datetime.widget: mobiscroll
    form.type.datetime.format: ~
    # location
    form.type.location.widget: location-typeahead
    form.type.location.preferred_countries: ['FR']
    form.type.location.defaultCountry: 'FR'
    # Global Variables
    templating.globals.class: nmariani\Bundle\BootstrappBundle\Templating\GlobalVariables
    # KnpMenu
    knp_menu.renderer.twig.class: nmariani\Bundle\BootstrappBundle\Menu\Renderer\TwigRenderer
    knp_menu.renderer.twig.template: BootstrappBundle:Menu:knp_menu.html.twig

services:
    form.type.date:
        class: nmariani\Bundle\BootstrappBundle\Form\Type\DateType
        #scope: prototype
        tags: [{ name: form.type, alias: date }]
        calls:
            - [ setDefaultWidget, [ %form.type.date.widget% ] ]
            - [ setDefaultFormat, [ %form.type.date.format% ] ]
            - [ setAssetsLoader, [ @assets_loader ] ]
    form.type.time:
        class: nmariani\Bundle\BootstrappBundle\Form\Type\TimeType
        #scope: prototype
        tags: [{ name: form.type, alias: time }]
        calls:
            - [ setDefaultWidget, [ %form.type.time.widget% ] ]
            - [ setDefaultFormat, [ %form.type.time.format% ] ]
            - [ setAssetsLoader, [ @assets_loader ] ]
    form.type.datetime:
        class: nmariani\Bundle\BootstrappBundle\Form\Type\DateTimeType
        #scope: prototype
        tags: [{ name: form.type, alias: datetime }]
        calls:
            - [ setDefaultWidget, [ %form.type.datetime.widget% ] ]
            - [ setDefaultFormat, [ %form.type.datetime.format% ] ]
            - [ setAssetsLoader, [ @assets_loader ] ]
    form.type.choice:
        class: nmariani\Bundle\BootstrappBundle\Form\Type\ChoiceType
        #scope: prototype
        tags: [{ name: form.type, alias: choice }]
        calls:
            - [ setDefaultWidget, [ %form.type.choice.widget% ] ]
            - [ setAssetsLoader, [ @assets_loader ] ]
    form.type.location:
        class: nmariani\Bundle\BootstrappBundle\Form\Type\LocationType
        #scope: prototype
        tags: [{ name: form.type, alias: bootstrapp_bundle_location }]
        calls:
            - [ setContainer, [ @service_container ] ]
            - [ setDefaultWidget, [ %form.type.location.widget% ] ]
            - [ setAssetsLoader, [ @assets_loader ] ]
    form.type.ckeditor:
        class: %bootstrapp.ckeditor.class%
        #scope: prototype
        tags: [{ name: form.type, alias: bootstrapp_bundle_ckeditor }]
        calls:
            - [ setContainer, [ @service_container ] ]
            - [ setAssetsLoader, [ @assets_loader ] ]
    form.type.file:
        class: nmariani\Bundle\BootstrappBundle\Form\Type\FileType
        tags: [{ name: form.type, alias: file }]
        calls:
            - [ setAssetsLoader, [ @assets_loader ] ]
            - [ setContainer, [ @service_container ] ]
    assets_loader:
        class: nmariani\Bundle\BootstrappBundle\Templating\Loader\AssetsLoader
